# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - yarn install
  - echo -n "$NEXT_CONFIG_FILE" | base64 --decode > next.config.js
pages:
  environments:
    name: staging
    url: https://gaetan1903..gitlab.io/web-ranking/
  script:
    - yarn build
    - mv out/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
