# The Docker image that will be used to build your app
image: node:lts

stages:
  - build
  - deploy

build-job:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  script:
    - yarn install
    - yarn build || exit 1

.deploy-job: &deploy-job
  script:
    - apt-get update -y -qq
    - apt-get install -y -qq sshpass
    - export SSHPASS=$PASSWORD_SERVER
    - |
      sshpass -e ssh -t -oStrictHostKeyChecking=no "$USER_SERVER@$HOST_SERVER" <<EOF
        cd $PROJECT_DIR
        git pull
        yarn install
        yarn build
        pm2 restart web-ranking --update-env
      EOF

deploy-to-staging:
  <<: *deploy-job
  variables:
    PROJECT_DIR: web-ranking
    HOST_SERVER: ${HOST_PREPROD}
  stage: deploy
  environment:
    name: staging
  only:
    - main

deploy-to-production:
  <<: *deploy-job
  variables:
    PROJECT_DIR: /opt/web-ranking
    HOST_SERVER: ${HOST_PROD}
  stage: deploy
  when: manual
  environment:
    name: production
  only:
    - main
