# The Docker image that will be used to build your app
image: node:lts

before_script:
  - apt-get update -y -qq
  - apt-get install -y -qq sshpass
  - export SSHPASS=$PASSWORD_SERVER

deploy:
  script:
    - |
      sshpass -e ssh -t -oStrictHostKeyChecking=no "$USER_SERVER@$HOST_SERVER" <<EOF
        cd web-ranking
        git pull
        echo -n "$NEXT_CONFIG_FILE" | base64 --decode > next.config.js
        yarn install
        yarn build
        pm2 restart web-ranking --update-env
      EOF
  only:
    - main
